# Generated by Django 5.2.12 on 2026-03-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('type', models.CharField(choices=[('direct', 'Extração direta'), ('rag', 'RAG (Retrieval-Augmented Generation)')], max_length=20, verbose_name='tipo de pipeline')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('chunk_size', models.PositiveIntegerField(default=600, help_text='Tamanho aproximado do chunk em tokens (recomendado entre 500 e 800).', verbose_name='tamanho do chunk')),
                ('top_k', models.PositiveIntegerField(default=3, help_text='Número de chunks mais relevantes recuperados (3 ou 5).', verbose_name='top-k')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
            },
        ),
    ]
