# Generated by Django 5.2.12 on 2026-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('pdf_file', models.FileField(upload_to='documents/', verbose_name='arquivo PDF')),
                ('extracted_text', models.TextField(blank=True, verbose_name='texto extraído')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='data de upload')),
                ('num_pages', models.PositiveIntegerField(default=0, verbose_name='número de páginas')),
                ('human_tags', models.TextField(blank=True, help_text='Lista de palavras‑chave separadas por vírgula.', verbose_name='tags humanas (ground truth)')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-upload_date'],
            },
        ),
    ]
