# Generated by Django 5.2.12 on 2026-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome do modelo')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('other', 'Outro')], default='ollama', max_length=20, verbose_name='provider')),
                ('endpoint', models.URLField(blank=True, help_text='Ex.: http://localhost:11434 para Ollama.', verbose_name='endpoint')),
                ('model_size', models.CharField(blank=True, max_length=50, verbose_name='tamanho do modelo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Modelo LLM',
                'verbose_name_plural': 'Modelos LLM',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('text', models.TextField(verbose_name='texto do prompt')),
                ('is_default', models.BooleanField(default=False, help_text='Usado como prompt padrão nos experimentos.', verbose_name='é prompt padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
    ]
